#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SERVER_ID 100

#define CLIENT_BASE_PORT 1000
#define SERVER_PORT 999

#define MAX_NODES 100
#define MAX_MESSAGE_LENGTH 150

#define BROADCAST_RADIUS 3
#define TTL_LIMIT 64

#define INF INT_MAX

#endif // CONSTANTS_H